CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
RGBLIGHT_ENABLE = no

RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no

ONESHOT_ENABLE = yes
COMBO_ENABLE = yes
OLED_ENABLE = no
