CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
RGBLIGHT_ENABLE = no
AUTO_SHIFT_ENABLE = yes

RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no

# TAP_DANCE_ENABLE = yes
ONESHOT_ENABLE = yes
OLED_ENABLE = no
